import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Nexus Nova - Attendance Management System",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: '/background-image.webp', type: 'image/webp' },
      { url: '/background-image.webp', sizes: '32x32', type: 'image/webp' },
      { url: '/background-image.webp', sizes: '16x16', type: 'image/webp' }
    ],
    shortcut: '/background-image.webp',
    apple: '/background-image.webp',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
